_wandb:
    value:
        cli_version: 0.23.1
        e:
            34jcc77xl07zsjyhfk24atkxgba05bj7:
                args:
                    - --data-dir
                    - data/processed/train
                codePath: src/xray_image_classifier/train.py
                codePathLocal: src/xray_image_classifier/train.py
                email: ritammoreiradasilva@gmail.com
                executable: /Users/rita/Documents/MLOPs/MLOps_88/.venv/bin/python3
                git:
                    commit: c069cb630226738c6a347136ee84a15a597dfdc3
                    remote: https://github.com/SamuelTavares8/MLOps_88.git
                host: MacBook-Pro-de-Rita.local
                os: macOS-26.2-arm64-arm-64bit-Mach-O
                program: /Users/rita/Documents/MLOPs/MLOps_88/src/xray_image_classifier/train.py
                python: CPython 3.13.11
                root: /Users/rita/Documents/MLOPs/MLOps_88
                startedAt: "2026-01-12T12:46:29.629670Z"
                writerId: 34jcc77xl07zsjyhfk24atkxgba05bj7
        m: []
        python_version: 3.13.11
        t:
            "1":
                - 1
                - 41
                - 48
                - 105
            "2":
                - 1
                - 41
                - 48
                - 105
            "3":
                - 16
            "4": 3.13.11
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 16
epochs:
    value: 10
learning_rate:
    value: 0.0001
